---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
  name: node-red
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 31880
    port: 1880
    protocol: TCP
    targetPort: 1880
  selector:
    app: node-red
  type: NodePort
