---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: default
  labels:
    app: bazarr
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.bazarr: glob:amd64-v*
spec:
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: linuxserver/bazarr:amd64-v0.8.4.3-ls74
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6767
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/Amsterdam
        volumeMounts:
          - name: bazarr-config
            mountPath: /config
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: local-path-pvc
