---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: bazarr
  name: bazarr
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 6767
    port: 6767
    protocol: TCP
    targetPort: 6767
  selector:
    app: bazarr
  type: NodePort
