---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-bazarr-config
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.1
    path: "/mnt/usb2/K8S/APPS/bazarr/config/"
