---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    git: ssh://git@github.com/longhorn/longhorn
    ref: master
    path: chart
