---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 15.4.6
  values:
    prometheus:
      prometheusSpec:
        externalUrl: localhost:9090
